// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqyx8aUKSzOuckhdBUC4N_ULfWD_T7k8',
    appId: '1:33965675312:web:f22b2067f3150eaebaaef5',
    messagingSenderId: '33965675312',
    projectId: 'taamm-1726f',
    authDomain: 'taamm-1726f.firebaseapp.com',
    storageBucket: 'taamm-1726f.appspot.com',
    measurementId: 'G-8JJGQBY8WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MInpSR13P1QVGOcj8N7EQQWR8v7zKaQ',
    appId: '1:33965675312:android:699f72f5e69deb2cbaaef5',
    messagingSenderId: '33965675312',
    projectId: 'taamm-1726f',
    storageBucket: 'taamm-1726f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRqXaiLUpCTj9K7zmv-z543XX8wFP3yLU',
    appId: '1:33965675312:ios:b8fa73ddb3523949baaef5',
    messagingSenderId: '33965675312',
    projectId: 'taamm-1726f',
    storageBucket: 'taamm-1726f.appspot.com',
    iosClientId: '33965675312-2kloouolgcldpiu4m3bjijagm2qiuttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.taamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRqXaiLUpCTj9K7zmv-z543XX8wFP3yLU',
    appId: '1:33965675312:ios:e02a194e7b46fec7baaef5',
    messagingSenderId: '33965675312',
    projectId: 'taamm-1726f',
    storageBucket: 'taamm-1726f.appspot.com',
    iosClientId: '33965675312-ua8tochsepsq14pag2r4bpgesk45kt59.apps.googleusercontent.com',
    iosBundleId: 'com.example.taamApp.RunnerTests',
  );
}
